import type { Metadata } from "next";
import "./globals.css";
import "@/app/login/styles.scss"
import Menu from "@/components/common/side_bar/side_bar";

export const metadata: Metadata = {
  title: "jp next",
  description: "Generated by JP next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Menu />
        {children}
      </body>
    </html>
  );
}
